import { defineStore } from "pinia";

export const useUserFriendsStore = defineStore("userFriends", {
  state: () => ({
    friendsMoodUpdateList: [
      {
        id: 1,
        user_id: 1,
        name: "fulano silva sauro noem grandes",
        username: "fulano",
        mood: 50,
        hunger: 50,
        boredom: 50,
        physicalDisposition: 50,
        emotionalDisposition: 50,
        willingnessToTalk: 50,
        willingnessToListen: 50,
        beAlone: 50,
        observation:
          " fulano 1 obsdsd s sajidnsa das dsandjnsaudn sandnas dnunasudb",

        time: "1h",
      },
      {
        id: 2,
        user_id: 2,
        name: "beltrano",
        username: "beltrado",
        mood: 55,
        hunger: 56,
        boredom: 5,
        physicalDisposition: 1,
        emotionalDisposition: 20,
        willingnessToTalk: 60,
        willingnessToListen: 30,
        beAlone: 50,
        observation: " beltrano sdobnsa d  duibas diuas asbdiub",
        time: "2h",
      },
      {
        id: 3,
        user_id: 2,
        name: "beltrano",
        username: "beltrado",
        mood: 55,
        hunger: 56,
        boredom: 5,
        physicalDisposition: 1,
        emotionalDisposition: 20,
        willingnessToTalk: 60,
        willingnessToListen: 30,
        beAlone: 50,
        observation: " beltrano sdobnsa d  duibas diuas asbdiub",
        time: "1h",
      },
      {
        id: 4,
        user_id: 2,
        name: "beltrano",
        username: "beltrado",
        mood: 55,
        hunger: 56,
        boredom: 5,
        physicalDisposition: 1,
        emotionalDisposition: 20,
        willingnessToTalk: 60,
        willingnessToListen: 30,
        beAlone: 50,
        observation: " beltrano sdobnsa d  duibas diuas asbdiub",
        time: "22h",
      },
      {
        id: 5,
        user_id: 2,
        name: "beltrano",
        username: "beltrado",
        mood: 55,
        hunger: 56,
        boredom: 5,
        physicalDisposition: 1,
        emotionalDisposition: 20,
        willingnessToTalk: 60,
        willingnessToListen: 30,
        beAlone: 50,
        observation:
          " beltrano sdobada asdiuashd sand sauind yuabsdybu asdbnsa d  duibas diuas asbdiub",
        time: "23min",
      },
    ],
  }),
  actions: {},
});
